<?php

namespace Database\Seeders;

use App\Models\Asnaf;
use App\Models\RT;
use Illuminate\Database\Seeder;

class AsnafSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * Data migrated from React MVP localStorage
     * Total: 265 Asnaf entries from Desa Kandri RW 01
     */
    public function run(): void
    {
        // Clear existing data to prevent duplicates
        Asnaf::query()->delete();

        // Get RT IDs for foreign key mapping
        $rtMap = RT::pluck('id', 'kode')->toArray();

        $asnafData = [
            ['rt_id' => $rtMap['01'], 'nama' => 'Bariyah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Iuqmanul hakim', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'muniah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Maryono BU', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Suwarto', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Ahmad Rohimin', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Trianah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Tuyono', 'kategori' => 'Fakir', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Bardi', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Rokhmah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Teguh', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Sukadi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'A.Riyadi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Mesiri', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Tugiran', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Supriyoso', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Harsoyo', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Slamet', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Masruri', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Rojab', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Rukanah', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Basuki', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Hadi karnoto', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Yusuf', 'kategori' => 'Miskin', 'jumlah_jiwa' => 6, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Someri', 'kategori' => 'Miskin', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Asbari', 'kategori' => 'Miskin', 'jumlah_jiwa' => 6, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Suyanti', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Makhali', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Bani', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Sari (Bani)', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Kuwadi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Ihsanudin', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Ahmariyanto', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Maksum', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Bowo', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Nur Kholis', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Sis Samiyo', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Andi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Tukini', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Kuncarno', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Sujiati', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Suyatno', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Slamet Riyanto', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Khoiri', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Siswo Susanto', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'M.rozi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Endah', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Kamsidi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Yudi Prasetyo', 'kategori' => 'Miskin', 'jumlah_jiwa' => 6, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Bu Ayuk', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Much vera', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Muyanah', 'kategori' => 'Miskin', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Pawito', 'kategori' => 'Fakir', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Maryo', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Mbah Yem', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Lasiyem', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Sulikah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Romlah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Kang Basari', 'kategori' => 'Fakir', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Kayatun', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Mbah Maryam', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Margoyono', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Sutrisno', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Ribut', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Cahyono', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Sariadi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Pujiyanto', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Supariyah', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Indrayati', 'kategori' => 'Miskin', 'jumlah_jiwa' => 7, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Riadin Yuhri', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Sumaryadi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Ardiyah', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Siti Maesyaroh', 'kategori' => 'Miskin', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Wagiyan', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Siti Fatimah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Nurhayati', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Erna', 'kategori' => 'Fakir', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Hartono', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Yumaroh', 'kategori' => 'Fakir', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Masud/Tuginem', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Srikanti', 'kategori' => 'Fakir', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Lek Satmsi', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Eni Wati', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Ruslan', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Bunain', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Kusnah', 'kategori' => 'Miskin', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Nuriono', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Muhaeri', 'kategori' => 'Miskin', 'jumlah_jiwa' => 6, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Sapuan', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Kiswanto', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Yatinah', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Zarkoni', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Asrori', 'kategori' => 'Miskin', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Tasmiah', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Roni', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Muari', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Maskur', 'kategori' => 'Miskin', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Sugianto', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Azzari', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Karyono', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Junarso', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Ngatini', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Riyatun (Bojone Mbah Yor)', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Mbah Juari', 'kategori' => 'Fakir', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Mardi bin wakiman', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Mbar', 'kategori' => 'Fakir', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Aripin', 'kategori' => 'Fakir', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Nuriati', 'kategori' => 'Fakir', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Narang', 'kategori' => 'Fakir', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Mbah Sukarni', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Lipah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Musri', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Musriah', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Karnik', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Taat', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Sutrimo', 'kategori' => 'Miskin', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Buri Taat/Hasto', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Sudarsini', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Yati', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Markonah/Bejo (alm)', 'kategori' => 'Miskin', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Amin Hudi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Naimin', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Hudayani', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Sahid', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Ningsih', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Lasni', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Musiah', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Doni', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Nur Ali', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Yanti', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Budi Suhadi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Tri Handoyo', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Sulistiyono', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Khoirudin Alm', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Basari', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Doni Painem', 'kategori' => 'Miskin', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Sariyati', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Eva Santo', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Suhadi', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Sutinah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Supari', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Gini', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Mbah Yem', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Miftah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Muntazi', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Nur Hafidz', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Amiin Tauhid', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Rusmadi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Badri', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Rizki / Kisut', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Sunardi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Nila Amalia', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Tedi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Samroni', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Warsidi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Ahmat Riyadi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Rokib', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Siti Rohayati', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Budi Wahono', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Mukaeri', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Eko Marwanto', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Karsiah', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Sri Nasipah', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Sukarnin', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Juadi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Suyanto', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Sutanto', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Karsiyah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Kasman', 'kategori' => 'Fakir', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Agus Budiarto', 'kategori' => 'Fakir', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Martiah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Kastinah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Suyadi', 'kategori' => 'Fakir', 'jumlah_jiwa' => 6, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Purwanti Kastinah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Eni Kastinah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Surtini', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Sugiyanto', 'kategori' => 'Fakir', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Ainul Maksum', 'kategori' => 'Fakir', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Arisatun / Naryo', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Wartinah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Sudiono', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Luna / Tri Riyanto', 'kategori' => 'Fakir', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Karim', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Parmisih', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Kusriati / Kodir (Alm)', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Solikati', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Badriah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Siti Kustiani', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Satari', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Siti Kalimah', 'kategori' => 'Miskin', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Sugiman', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Karsan', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Lestari', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Sugiri', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Jahudi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Komari Ban', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Tumidi', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Kaswan', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Makhfudin', 'kategori' => 'Miskin', 'jumlah_jiwa' => 4, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Sukari Sutar', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Ghufron', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Bejo', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Feri', 'kategori' => 'Miskin', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Riati', 'kategori' => 'Miskin', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Neatermi', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Hadi Suroto', 'kategori' => 'Fakir', 'jumlah_jiwa' => 5, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Suparti', 'kategori' => 'Fakir', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Rukiyah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Jimi', 'kategori' => 'Fakir', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Nur Rokhim', 'kategori' => 'Fakir', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Priska', 'kategori' => 'Fakir', 'jumlah_jiwa' => 3, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Asiyah / Alm Palal', 'kategori' => 'Fakir', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Sunah', 'kategori' => 'Fakir', 'jumlah_jiwa' => 2, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'KH Supriyanto', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Santoso', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Zamsuri', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Nastain', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'KH Syarifudin Rowiyan', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Muhyidin', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Ust.Hasan Abadi', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Jumain', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Zuroh Imanudin', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Mat Saefudin', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Slamet', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'KH Maqsudi', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Arif Mahfudzi', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Ust. Zainuri', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Muthohar', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'KH Supriyadi', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'A.Masikun', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Bapak Rowi', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'H.Matori', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Tri Handayani', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'M.P Wibowo', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Pujiono Imam Fakhrudin', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'H.Nur Aeni', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Nur Rohim', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Muslih', 'kategori' => 'Fisabilillah', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'M.Idi Kurnianto', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Lutfi', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Masduki', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Yazid Maqsudi', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Pandu', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Bapak Sukadi', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Bapak Kodrat', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Bapak Samsudin', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Sunariadi', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Andi', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Sunawar', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['01'], 'nama' => 'Badawi', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Dul Muin', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Sokib', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['02'], 'nama' => 'Muis', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Mat Nawawi', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['03'], 'nama' => 'Amin Taufik', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Prayogi', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Tukimin', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['04'], 'nama' => 'Saeful', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Azis', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['05'], 'nama' => 'Sugeng', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Khoirul Basor', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Basari', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['06'], 'nama' => 'Surahmat', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Darman', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
            ['rt_id' => $rtMap['07'], 'nama' => 'Niman', 'kategori' => 'Amil', 'jumlah_jiwa' => 1, 'tahun' => 2026, 'status' => 'active'],
        ];

        foreach ($asnafData as $asnaf) {
            Asnaf::create($asnaf);
        }

        $this->command->info('✅ Successfully seeded ' . count($asnafData) . ' Asnaf entries');
        
        // Show statistics
        $stats = Asnaf::selectRaw('kategori, COUNT(*) as count, SUM(jumlah_jiwa) as total_jiwa')
            ->groupBy('kategori')
            ->get();
            
        $this->command->info('📊 Breakdown by kategori:');
        foreach ($stats as $stat) {
            $this->command->info("   {$stat->kategori}: {$stat->count} KK, {$stat->total_jiwa} jiwa");
        }
    }
}
