<?php

use App\Models\User;
use App\Models\Person;
use App\Models\Assignment;
use App\Models\OrganizationStructure;
use Illuminate\Support\Facades\DB;

require __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

$email = 'fajarmaqbulkandri@gmail.com';

DB::transaction(function () use ($email) {
    // 1. Find User
    $user = User::where('email', $email)->first();
    if (!$user) {
        echo "Error: User with email $email not found.\n";
        exit;
    }
    echo "User found: " . $user->name . " (ID: " . $user->id . ")\n";

    // 2. Find or Create Person
    $person = Person::where('user_id', $user->id)->first();
    if (!$person) {
        $person = Person::create([
            'user_id' => $user->id,
            'name' => $user->name,
            'nik' => '1234567890' . rand(1000, 9999), // Dummy NIK
            'gender' => 'L',
            'status' => 'Aktif',
            'phone' => '08123456789',
            'address' => 'Generated by System'
        ]);
        echo "Person record created (ID: " . $person->id . ").\n";
    } else {
        echo "Person record already exists (ID: " . $person->id . ").\n";
    }

    // 3. Find or Create Organization Structure
    // We need a structure for "Pengurus Harian" or similar to attach the assignment
    $structure = OrganizationStructure::firstOrCreate(
        ['name' => 'Pengurus Harian'],
        [
            'parent_id' => null,
            'description' => 'Struktur Utama',
            'level' => 1
        ]
    );
    echo "Organization Structure used: " . $structure->name . " (ID: " . $structure->id . ")\n";

    // 4. Create Assignment (Ketua Umum => Super Admin)
    // Deactivate old assignments for this person to be safe
    Assignment::where('person_id', $person->id)->update(['status' => 'Nonaktif']);

    $assignment = Assignment::create([
        'person_id' => $person->id,
        'structure_id' => $structure->id,
        'jabatan' => 'Ketua Umum', // This triggers Super Admin in frontend
        'status' => 'Aktif',
        'tipe_sk' => 'SK Pengangkatan',
        'no_sk' => '001/SK/BM/2026',
        'tanggal_mulai' => now(),
        'kewenangan' => ['super_admin' => true]
    ]);

    echo "Assignment created successfully!\n";
    echo "Role: Ketua Umum (Super Admin)\n";
    echo "Assignment ID: " . $assignment->id . "\n";
});
