<?php

use App\Models\User;
use App\Models\Person;
use App\Models\Assignment;
use App\Models\OrganizationStructure;
use Illuminate\Support\Facades\DB;

require __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

$email = 'fajarmaqbulkandri@gmail.com';

DB::transaction(function () use ($email) {
    // 1. Find User
    $user = User::where('email', $email)->first();
    if (!$user) {
        echo "Error: User with email $email not found.\n";
        exit;
    }
    echo "User found: " . $user->name . " (ID: " . $user->id . ")\n";

    // 2. Find or Create Person
    $person = Person::where('user_id', $user->id)->first();
    if (!$person) {
        // Based on previous error: people.nama_lengkap
        $person = Person::create([
            'user_id' => $user->id,
            'nama_lengkap' => $user->name, // Changed from name to nama_lengkap
            'nik' => '1234567890' . rand(1000, 9999),
            'jenis_kelamin' => 'L', // Assuming gender/jenis_kelamin field
            'status_pernikaan' => 'Belum Menikah', // Warning: Check schema if this fails
            'tempat_lahir' => 'Jakarta',
            'tanggal_lahir' => '1990-01-01',
            'alamat' => 'Generated by System',
            'no_hp' => '08123456789',
            'status' => 'Aktif'
        ]);
        echo "Person record created (ID: " . $person->id . ").\n";
    } else {
        echo "Person record already exists (ID: " . $person->id . ").\n";
    }

    // 3. Find or Create Organization Structure
    // Changed fields: name -> nama_struktur, description -> deskripsi
    $structure = OrganizationStructure::firstOrCreate(
        ['nama_struktur' => 'Pengurus Harian'],
        [
            'parent_id' => null,
            'deskripsi' => 'Struktur Utama',
            'kode_struktur' => 'PH-' . rand(100, 999), 
             // Add other required fields if any (check migration if possible, but firstOrcreate implies optional or default)
            'status' => 'Aktif',
            'is_active' => true 
        ]
    );
    echo "Organization Structure used: " . $structure->nama_struktur . " (ID: " . $structure->id . ")\n";

    // 4. Create Assignment (Ketua Umum => Super Admin)
    Assignment::where('person_id', $person->id)->update(['status' => 'Nonaktif']);

    $assignment = Assignment::create([
        'person_id' => $person->id,
        'structure_id' => $structure->id,
        'jabatan' => 'Ketua Umum', 
        'status' => 'Aktif',
        'tipe_sk' => 'SK Pengangkatan',
        'no_sk' => '001/SK/BM/2026',
        'tanggal_mulai' => now(),
        'kewenangan' => ['super_admin' => true]
    ]);

    echo "Assignment created successfully!\n";
    echo "Role: Ketua Umum (Super Admin)\n";
    echo "Assignment ID: " . $assignment->id . "\n";
});
